# Generated by Django 5.2.10 on 2026-03-31 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_rename_pre_trb3_weatherdata_pressure_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weatherdata",
            name="density_horizontal",
            field=models.FloatField(blank=True, null=True, verbose_name="水平观测带雪密度"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="density_slape",
            field=models.FloatField(blank=True, null=True, verbose_name="斜向观测带雪密度"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_avg_100cm",
            field=models.FloatField(blank=True, null=True, verbose_name="100cm风吹雪平均通量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_avg_200cm",
            field=models.FloatField(blank=True, null=True, verbose_name="200cm风吹雪平均通量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_cum_100cm",
            field=models.FloatField(blank=True, null=True, verbose_name="100cm风吹雪通量总量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_cum_200cm",
            field=models.FloatField(blank=True, null=True, verbose_name="200cm风吹雪通量总量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_max_100cm",
            field=models.FloatField(blank=True, null=True, verbose_name="100cm风吹雪最大通量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_max_200cm",
            field=models.FloatField(blank=True, null=True, verbose_name="200cm风吹雪最大通量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_min_100cm",
            field=models.FloatField(blank=True, null=True, verbose_name="100cm风吹雪最小通量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_min_200cm",
            field=models.FloatField(blank=True, null=True, verbose_name="200cm风吹雪最小通量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_std_100cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="100cm风吹雪通量标准差"
            ),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="flux_std_200cm",
            field=models.FloatField(
                blank=True, null=True, verbose_name="200cm风吹雪通量标准差"
            ),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="ice_content_horizontal",
            field=models.FloatField(blank=True, null=True, verbose_name="水平观测带冰含量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="ice_content_slape",
            field=models.FloatField(blank=True, null=True, verbose_name="斜向观测带冰含量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="snow_density_ssg",
            field=models.FloatField(blank=True, null=True, verbose_name="SSG雪密度"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="snow_depth_sr50a",
            field=models.FloatField(blank=True, null=True, verbose_name="SR50A雪深"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="snow_depth_ush",
            field=models.FloatField(blank=True, null=True, verbose_name="USH-9雪深"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="swe_horizontal",
            field=models.FloatField(blank=True, null=True, verbose_name="水平观测带雪水当量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="swe_slape",
            field=models.FloatField(blank=True, null=True, verbose_name="斜向观测带雪水当量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="swe_ssg",
            field=models.FloatField(blank=True, null=True, verbose_name="SSG雪水当量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="water_content_horizontal",
            field=models.FloatField(blank=True, null=True, verbose_name="水平观测带水含量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="water_content_slape",
            field=models.FloatField(blank=True, null=True, verbose_name="斜向观测带水含量"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_avg_100cm",
            field=models.FloatField(blank=True, null=True, verbose_name="100cm平均风速"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_avg_200cm",
            field=models.FloatField(blank=True, null=True, verbose_name="200cm平均风速"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_max_100cm",
            field=models.FloatField(blank=True, null=True, verbose_name="100cm最大风速"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_max_200cm",
            field=models.FloatField(blank=True, null=True, verbose_name="200cm最大风速"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_min_100cm",
            field=models.FloatField(blank=True, null=True, verbose_name="100cm最小风速"),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="wind_min_200cm",
            field=models.FloatField(blank=True, null=True, verbose_name="200cm最小风速"),
        ),
    ]
