# Generated by Django 5.2.10 on 2026-04-22 11:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_weatherdata_density_horizontal_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operated_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="操作时间",
                    ),
                ),
                ("data_at", models.DateTimeField(verbose_name="数据时间")),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=6, max_digits=20, verbose_name="数据值"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="manual_data_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人员",
                    ),
                ),
            ],
            options={
                "ordering": ["-data_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("operator", "data_at"),
                        name="uniq_manual_data_operator_data_at",
                    )
                ],
            },
        ),
    ]
