# Generated by Django 5.2.10 on 2026-04-23 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_manualdatarecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="manualdatarecord",
            name="uniq_manual_data_operator_data_at",
        ),
        migrations.AddField(
            model_name="manualdatarecord",
            name="is_void",
            field=models.BooleanField(default=False, verbose_name="是否作废"),
        ),
        migrations.AddField(
            model_name="manualdatarecord",
            name="voided_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="作废时间"),
        ),
        migrations.AddField(
            model_name="manualdatarecord",
            name="voided_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="voided_manual_data_records",
                to=settings.AUTH_USER_MODEL,
                verbose_name="作废操作人",
            ),
        ),
        migrations.AddConstraint(
            model_name="manualdatarecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_void", False)),
                fields=("operator", "data_at"),
                name="uniq_manual_data_operator_data_at",
            ),
        ),
    ]
