# Generated by Django 5.1.15 on 2026-09-09 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_weatherdailyagg_weatherhourlyagg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherdailyagg',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='daily_aggregates', to='data.station', verbose_name='站点'),
        ),
        migrations.AlterField(
            model_name='weatherhourlyagg',
            name='station',
            field=models.ForeignKey(db_column='station_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='hourly_aggregates', to='data.station', verbose_name='站点'),
        ),
    ]
