# Generated by Django 5.1.15 on 2026-09-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_alter_weatherdailyagg_station_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='t_soil_150cm',
            field=models.FloatField(blank=True, null=True, verbose_name='土壤温度(150cm)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='t_soil_30cm',
            field=models.FloatField(blank=True, null=True, verbose_name='土壤温度(30cm)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='t_soil_80cm',
            field=models.FloatField(blank=True, null=True, verbose_name='土壤温度(80cm)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='trb3_rh',
            field=models.FloatField(blank=True, null=True, verbose_name='TRB3相对湿度'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='trb3_ta',
            field=models.FloatField(blank=True, null=True, verbose_name='TRB3空气温度'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='vwc_soil_150cm',
            field=models.FloatField(blank=True, null=True, verbose_name='土壤含水量(150cm)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='vwc_soil_30cm',
            field=models.FloatField(blank=True, null=True, verbose_name='土壤含水量(30cm)'),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='vwc_soil_80cm',
            field=models.FloatField(blank=True, null=True, verbose_name='土壤含水量(80cm)'),
        ),
    ]
