# Generated by Django 5.1.15 on 2026-09-10 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='会话标题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后活跃时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_chat_sessions', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AiChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '用户'), ('assistant', 'AI 助手')], max_length=16, verbose_name='角色')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.aichatsession', verbose_name='所属会话')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AiAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=50, verbose_name='工具名称')),
                ('question', models.TextField(verbose_name='用户问题')),
                ('generated_sql', models.TextField(blank=True, verbose_name='生成的 SQL')),
                ('tables_used', models.JSONField(blank=True, default=list, verbose_name='涉及的表')),
                ('row_count', models.IntegerField(blank=True, null=True, verbose_name='返回行数')),
                ('duration_ms', models.IntegerField(blank=True, null=True, verbose_name='耗时(毫秒)')),
                ('status', models.CharField(choices=[('success', '成功'), ('blocked', '被安全策略拦截'), ('error', '执行出错')], default='success', max_length=16, verbose_name='状态')),
                ('detail', models.TextField(blank=True, verbose_name='附加信息/错误原因')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作人')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='ai_assistant.aichatsession', verbose_name='所属会话')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
