# Generated by Django 5.2.10 on 2026-02-04 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="数据存储时间")),
                (
                    "record",
                    models.IntegerField(blank=True, null=True, verbose_name="记录号"),
                ),
                (
                    "batt_volt",
                    models.FloatField(blank=True, null=True, verbose_name="数采电池电压"),
                ),
                (
                    "ptemp",
                    models.FloatField(blank=True, null=True, verbose_name="数采面板温度"),
                ),
                ("ws", models.FloatField(blank=True, null=True, verbose_name="风速")),
                ("wd", models.FloatField(blank=True, null=True, verbose_name="风向")),
                (
                    "wd_std",
                    models.FloatField(blank=True, null=True, verbose_name="风向标准差"),
                ),
                ("ta", models.FloatField(blank=True, null=True, verbose_name="空气温度")),
                ("rh", models.FloatField(blank=True, null=True, verbose_name="空气相对湿度")),
                (
                    "pvapor",
                    models.FloatField(blank=True, null=True, verbose_name="水汽压"),
                ),
                (
                    "pre_trb3",
                    models.FloatField(blank=True, null=True, verbose_name="大气压"),
                ),
                ("sw_in", models.FloatField(blank=True, null=True, verbose_name="总辐射")),
                (
                    "vwc_soil_10cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤含水量1(10cm)"
                    ),
                ),
                (
                    "vwc_soil_20cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤含水量2(20cm)"
                    ),
                ),
                (
                    "vwc_soil_40cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤含水量3(40cm)"
                    ),
                ),
                (
                    "vwc_soil_60cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤含水量4(60cm)"
                    ),
                ),
                (
                    "vwc_soil_100cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤含水量5(100cm)"
                    ),
                ),
                (
                    "t_soil_10cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤温度1(10cm)"
                    ),
                ),
                (
                    "t_soil_20cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤温度2(20cm)"
                    ),
                ),
                (
                    "t_soil_40cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤温度3(40cm)"
                    ),
                ),
                (
                    "t_soil_60cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤温度4(60cm)"
                    ),
                ),
                (
                    "t_soil_100cm",
                    models.FloatField(
                        blank=True, null=True, verbose_name="土壤温度5(100cm)"
                    ),
                ),
                (
                    "rain_snow",
                    models.FloatField(blank=True, null=True, verbose_name="降水累计值"),
                ),
                (
                    "rain_snow_half_hour",
                    models.FloatField(blank=True, null=True, verbose_name="半小时降水"),
                ),
                (
                    "snow_depth",
                    models.FloatField(blank=True, null=True, verbose_name="雪深"),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weather_data",
                        to="data.station",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "unique_together": {("station", "timestamp")},
            },
        ),
    ]
