# Generated by Django 5.2.10 on 2026-02-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="weatherdata",
            old_name="pre_trb3",
            new_name="pressure",
        ),
        migrations.RenameField(
            model_name="weatherdata",
            old_name="rain_snow",
            new_name="rainsnow",
        ),
        migrations.RenameField(
            model_name="weatherdata",
            old_name="rain_snow_half_hour",
            new_name="rainsnow_halfhour",
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="snow_density",
            field=models.FloatField(
                blank=True, help_text="单位：kg/m³", null=True, verbose_name="雪密度"
            ),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="swe",
            field=models.FloatField(
                blank=True, help_text="单位：mm", null=True, verbose_name="雪水当量"
            ),
        ),
    ]
