# Generated by Django 5.2.10 on 2026-04-23 10:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "data",
            "0005_remove_manualdatarecord_uniq_manual_data_operator_data_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HydrologyForecastRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "run_id",
                    models.CharField(max_length=64, unique=True, verbose_name="运行编号"),
                ),
                ("target_date", models.DateField(verbose_name="预测日期")),
                (
                    "model_name",
                    models.CharField(blank=True, max_length=100, verbose_name="模型名称"),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, max_length=100, verbose_name="模型版本"),
                ),
                (
                    "source",
                    models.CharField(
                        default="scheduler", max_length=30, verbose_name="触发来源"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "运行中"),
                            ("success", "成功"),
                            ("failed", "失败"),
                        ],
                        default="running",
                        max_length=16,
                        verbose_name="运行状态",
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveSmallIntegerField(default=0, verbose_name="重试次数"),
                ),
                (
                    "record_count",
                    models.PositiveIntegerField(default=0, verbose_name="结果条数"),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="开始时间"
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hydrology_forecast_runs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发人",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HydrologyForecastDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("target_date", models.DateField(verbose_name="预测日期")),
                (
                    "flow_avg",
                    models.DecimalField(
                        decimal_places=3, max_digits=12, verbose_name="日均流量"
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="模型名称")),
                (
                    "model_version",
                    models.CharField(max_length=100, verbose_name="模型版本"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="hydrology_daily_forecasts",
                        to="data.station",
                        verbose_name="站点",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forecasts",
                        to="data.hydrologyforecastrun",
                        verbose_name="所属运行",
                    ),
                ),
            ],
            options={
                "ordering": ["-target_date", "station__name"],
            },
        ),
        migrations.AddIndex(
            model_name="hydrologyforecastrun",
            index=models.Index(
                fields=["target_date", "status"], name="data_hydrol_target__f65781_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="hydrologyforecastdaily",
            index=models.Index(
                fields=["target_date", "model_name", "model_version"],
                name="data_hydrol_target__51540d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="hydrologyforecastdaily",
            constraint=models.UniqueConstraint(
                fields=("station", "target_date", "model_name", "model_version"),
                name="uniq_hydro_daily_station_date_model_version",
            ),
        ),
    ]
