# Generated by Django 5.1.15 on 2026-07-22 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0006_hydrologyforecastrun_hydrologyforecastdaily_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeatherDailyAgg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("day", models.DateTimeField(verbose_name="日期")),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="data.station",
                        verbose_name="站点",
                    ),
                ),
                ("avg_ta", models.FloatField(null=True, verbose_name="日均温度")),
                ("max_ta", models.FloatField(null=True, verbose_name="日最高温度")),
                ("min_ta", models.FloatField(null=True, verbose_name="日最低温度")),
                ("avg_rh", models.FloatField(null=True, verbose_name="日均湿度")),
                ("max_rh", models.FloatField(null=True, verbose_name="日最大湿度")),
                ("min_rh", models.FloatField(null=True, verbose_name="日最小湿度")),
                ("avg_ws", models.FloatField(null=True, verbose_name="日均风速")),
                ("max_ws", models.FloatField(null=True, verbose_name="日最大风速")),
                ("avg_pressure", models.FloatField(null=True, verbose_name="日均气压")),
                ("total_rainsnow", models.FloatField(null=True, verbose_name="日累计降水")),
                (
                    "max_rainsnow_halfhour",
                    models.FloatField(null=True, verbose_name="日最大半时降水"),
                ),
                ("max_snow_depth", models.FloatField(null=True, verbose_name="日最大雪深")),
                (
                    "max_snow_depth_sr50a",
                    models.FloatField(null=True, verbose_name="日最大SR50A雪深"),
                ),
                (
                    "max_snow_depth_ush",
                    models.FloatField(null=True, verbose_name="日最大USH雪深"),
                ),
                ("avg_sw_in", models.FloatField(null=True, verbose_name="日均总辐射")),
                ("max_sw_in", models.FloatField(null=True, verbose_name="日最大总辐射")),
                (
                    "avg_vwc_10cm",
                    models.FloatField(null=True, verbose_name="日均土壤含水量10cm"),
                ),
                (
                    "avg_vwc_20cm",
                    models.FloatField(null=True, verbose_name="日均土壤含水量20cm"),
                ),
                (
                    "avg_vwc_40cm",
                    models.FloatField(null=True, verbose_name="日均土壤含水量40cm"),
                ),
                (
                    "avg_vwc_60cm",
                    models.FloatField(null=True, verbose_name="日均土壤含水量60cm"),
                ),
                (
                    "avg_vwc_100cm",
                    models.FloatField(null=True, verbose_name="日均土壤含水量100cm"),
                ),
                (
                    "avg_tsoil_10cm",
                    models.FloatField(null=True, verbose_name="日均土壤温度10cm"),
                ),
                (
                    "avg_tsoil_20cm",
                    models.FloatField(null=True, verbose_name="日均土壤温度20cm"),
                ),
                (
                    "avg_tsoil_40cm",
                    models.FloatField(null=True, verbose_name="日均土壤温度40cm"),
                ),
                (
                    "avg_tsoil_60cm",
                    models.FloatField(null=True, verbose_name="日均土壤温度60cm"),
                ),
                (
                    "avg_tsoil_100cm",
                    models.FloatField(null=True, verbose_name="日均土壤温度100cm"),
                ),
                ("max_swe", models.FloatField(null=True, verbose_name="日最大雪水当量")),
                (
                    "max_swe_ssg",
                    models.FloatField(null=True, verbose_name="日最大SSG雪水当量"),
                ),
                ("record_count", models.BigIntegerField(verbose_name="原始记录数")),
            ],
            options={
                "db_table": "weather_daily_agg",
                "ordering": ["-day", "station_id"],
                "managed": True,
                "unique_together": {("day", "station")},
            },
        ),
        migrations.CreateModel(
            name="WeatherHourlyAgg",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("hour", models.DateTimeField(verbose_name="小时")),
                (
                    "station",
                    models.ForeignKey(
                        db_column="station_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="data.station",
                        verbose_name="站点",
                    ),
                ),
                ("avg_ta", models.FloatField(null=True, verbose_name="小时均温度")),
                ("max_ta", models.FloatField(null=True, verbose_name="小时最高温度")),
                ("min_ta", models.FloatField(null=True, verbose_name="小时最低温度")),
                ("avg_rh", models.FloatField(null=True, verbose_name="小时均湿度")),
                ("avg_ws", models.FloatField(null=True, verbose_name="小时均风速")),
                ("max_ws", models.FloatField(null=True, verbose_name="小时最大风速")),
                ("avg_pressure", models.FloatField(null=True, verbose_name="小时均气压")),
                ("max_snow_depth", models.FloatField(null=True, verbose_name="小时最大雪深")),
                ("avg_sw_in", models.FloatField(null=True, verbose_name="小时均总辐射")),
                ("record_count", models.BigIntegerField(verbose_name="原始记录数")),
            ],
            options={
                "db_table": "weather_hourly_agg",
                "ordering": ["-hour", "station_id"],
                "managed": True,
                "unique_together": {("hour", "station")},
            },
        ),
    ]
